// This file is generated by scripts/generate-project-media-manifest.mjs.
// Do not edit it by hand. Add images under public/projects/{assetFolder}/ instead.

export type GeneratedProjectMediaEntry = {
  cover?: string;
  gallery: string[];
};

export const generatedProjectMediaManifest: Record<string, GeneratedProjectMediaEntry> = {
  "ai-group-detection": {
    "gallery": []
  },
  "automation-utilities": {
    "gallery": []
  },
  "mobile-job-portal": {
    "gallery": []
  },
  "portfolio-site": {
    "gallery": []
  },
  "ralskies-showcase": {
    "gallery": []
  },
  "smart-shelf": {
    "gallery": []
  }
};
